import { useState, useCallback } from 'react';
import { FileText, Download, Copy, Check } from 'lucide-react';
import type { ScanReport } from '@shared/types';
import { motion, AnimatePresence } from 'framer-motion';

interface Props {
  report: ScanReport;
}

export function generateMarkdown(report: ScanReport): string {
  const lines: string[] = [];
  lines.push(`# Agent Preflight Report — ${report.repoName}`);
  lines.push('');
  lines.push(`**Production Readiness Score:** ${report.score.percentage}%`);
  lines.push(`**Status:** ${report.status}`);
  lines.push(`**Duration:** ${(report.duration / 1000).toFixed(1)}s`);
  lines.push(`**Date:** ${new Date(report.timestamp).toISOString()}`);
  lines.push('');
  lines.push('## Score Breakdown');
  lines.push('');
  lines.push('| Category | Score | Status |');
  lines.push('|----------|-------|--------|');
  for (const cat of report.score.categories) {
    const status = cat.percentage >= 75 ? '✅' : cat.percentage >= 50 ? '⚠️' : '❌';
    lines.push(`| ${cat.label} | ${cat.percentage}% | ${status} |`);
  }
  lines.push('');
  lines.push('## Issues Found');
  lines.push('');
  for (const cat of report.categories) {
    const issues = cat.checks.filter(c => c.status === 'fail' || c.status === 'warn');
    if (issues.length === 0) continue;
    lines.push(`### ${cat.categoryLabel}`);
    lines.push('');
    for (const issue of issues) {
      lines.push(`- **${issue.message}**`);
      if (issue.file) lines.push(`  - File: \`${issue.file}${issue.line ? `:${issue.line}` : ''}\``);
      if (issue.suggestedFix) lines.push(`  - Fix: ${issue.suggestedFix}`);
    }
    lines.push('');
  }
  lines.push('---');
  lines.push('Generated by Agent Preflight');
  return lines.join('\n');
}

export function generateHTML(report: ScanReport): string {
  const catCards = report.score.categories.map(cat => `
    <div style="background:#18181b;border:1px solid #27272a;border-radius:6px;padding:12px;margin-bottom:8px;">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
        <span style="font-size:12px;font-weight:600;color:#a1a1aa;text-transform:uppercase;">${cat.label}</span>
        <span style="font-size:14px;font-weight:700;color:${cat.percentage >= 75 ? '#10b981' : cat.percentage >= 50 ? '#f59e0b' : '#ef4444'}">${cat.percentage}%</span>
      </div>
      <div style="height:4px;background:#27272a;border-radius:2px;overflow:hidden;">
        <div style="height:100%;width:${cat.percentage}%;background:${cat.percentage >= 75 ? '#10b981' : cat.percentage >= 50 ? '#f59e0b' : '#ef4444'};border-radius:2px;"></div>
      </div>
    </div>
  `).join('');

  const issueRows = report.categories.map(cat => {
    const issues = cat.checks.filter(c => c.status === 'fail' || c.status === 'warn');
    if (issues.length === 0) return '';
    return `
      <div style="margin-bottom:16px;">
        <h3 style="font-size:14px;font-weight:600;color:#f4f4f5;margin-bottom:8px;">${cat.categoryLabel}</h3>
        ${issues.map(i => `
          <div style="display:flex;align-items:flex-start;gap:8px;padding:8px 0;border-bottom:1px solid #27272a;">
            <span style="color:${i.status === 'fail' ? '#ef4444' : '#f59e0b'};font-size:14px;">${i.status === 'fail' ? '✕' : '⚠'}</span>
            <div>
              <div style="font-size:13px;color:#e4e4e7;">${i.message}</div>
              ${i.file ? `<div style="font-size:11px;color:#71717a;font-family:monospace;">${i.file}${i.line ? `:${i.line}` : ''}</div>` : ''}
            </div>
          </div>
        `).join('')}
      </div>
    `;
  }).join('');

  return `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><title>Preflight Report — ${report.repoName}</title>
<style>
body{font-family:Inter,system-ui,sans-serif;background:#09090b;color:#e4e4e7;max-width:800px;margin:0 auto;padding:40px 24px;}
h1{font-size:24px;font-weight:700;color:#f4f4f5;}
.score-circle{width:120px;height:120px;border-radius:50%;display:flex;align-items:center;justify-content:center;
background:conic-gradient(${report.score.percentage >= 75 ? '#10b981' : report.score.percentage >= 50 ? '#f59e0b' : '#ef4444'} ${report.score.percentage}%,#27272a 0);
}
.score-inner{width:100px;height:100px;border-radius:50%;background:#09090b;display:flex;flex-direction:column;align-items:center;justify-content:center;}
.score-num{font-size:28px;font-weight:800;color:#f4f4f5;}
.score-label{font-size:11px;color:#71717a;text-transform:uppercase;}
.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0;}
.summary-card{background:#18181b;border:1px solid #27272a;border-radius:6px;padding:12px;text-align:center;}
.summary-num{font-size:20px;font-weight:700;}
.meta{font-size:12px;color:#71717a;margin:16px 0;}
h2{font-size:16px;font-weight:600;color:#f4f4f5;margin:24px 0 12px;}
.cat-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;}
</style></head><body>
<h1>🔍 Preflight Report</h1>
<div class="meta">${report.repoName} · ${new Date(report.timestamp).toLocaleDateString()} · ${(report.duration / 1000).toFixed(1)}s</div>
<div style="display:flex;align-items:center;gap:24px;margin:24px 0;">
<div class="score-circle"><div class="score-inner"><div class="score-num">${report.score.percentage}%</div><div class="score-label">readiness</div></div></div>
<div>
<div style="font-size:14px;font-weight:600;color:#f4f4f5;margin-bottom:4px;">Production Readiness</div>
<div style="font-size:13px;color:#71717a;">${report.passedChecks}/${report.totalChecks} checks passing</div>
</div>
</div>
<div class="summary">
<div class="summary-card"><div class="summary-num" style="color:#10b981;">${report.passedChecks}</div><div style="font-size:11px;color:#71717a;">Passed</div></div>
<div class="summary-card"><div class="summary-num" style="color:#ef4444;">${report.failedChecks}</div><div style="font-size:11px;color:#71717a;">Failed</div></div>
<div class="summary-card"><div class="summary-num" style="color:#f59e0b;">${report.warningChecks}</div><div style="font-size:11px;color:#71717a;">Warnings</div></div>
</div>
<h2>Category Scores</h2>
<div class="cat-grid">${catCards}</div>
<h2>Issues</h2>
${issueRows || '<div style="color:#71717a;font-size:13px;">No issues found</div>'}
</body></html>`;
}

export function ReportExport({ report }: Props) {
  const [format, setFormat] = useState<'markdown' | 'json' | 'html'>('markdown');
  const [copied, setCopied] = useState(false);

  const content = format === 'markdown' ? generateMarkdown(report) :
    format === 'json' ? JSON.stringify(report, null, 2) :
    generateHTML(report);

  const filename = `preflight-${report.repoName.replace(/[^a-zA-Z0-9]/g, '-')}`;

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {}
  }, [content]);

  const handleDownload = useCallback(() => {
    const ext = format === 'markdown' ? 'md' : format === 'json' ? 'json' : 'html';
    const mime = format === 'html' ? 'text/html' : format === 'json' ? 'application/json' : 'text/markdown';
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  }, [content, format, filename]);

  return (
    <div className="panel p-4 space-y-3 animate-fadeIn">
      <div className="flex items-center gap-2">
        <FileText size={14} className="text-base-400" />
        <span className="text-[12px] font-semibold text-base-300 uppercase tracking-wider">Export Report</span>
      </div>

      {/* Format selector */}
      <div className="flex items-center gap-1 p-0.5 bg-base-950 rounded-md border border-base-800">
        {(['markdown', 'json', 'html'] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFormat(f)}
            className={`flex-1 px-3 py-1.5 rounded text-[11px] font-medium transition-colors ${
              format === f ? 'bg-base-800 text-base-200' : 'text-base-500 hover:text-base-300'
            }`}
          >
            {f.toUpperCase()}
          </button>
        ))}
      </div>

      {/* Preview */}
      <div className="panel !bg-base-950 rounded-md max-h-[200px] overflow-y-auto">
        <pre className="p-3 text-[11px] font-mono text-base-400 leading-relaxed whitespace-pre-wrap">
          <code>{content.slice(0, 500)}{content.length > 500 ? '...' : ''}</code>
        </pre>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-2">
        <button onClick={handleCopy} className="btn-ghost flex-1 justify-center text-[12px] py-2">
          {copied ? <Check size={13} className="text-emerald-400" /> : <Copy size={13} />}
          {copied ? 'Copied' : 'Copy'}
        </button>
        <button onClick={handleDownload} className="btn-ghost flex-1 justify-center text-[12px] py-2">
          <Download size={13} />
          Download
        </button>
      </div>
    </div>
  );
}
