import type { PreflightConfig } from "./types.js";

export const DEFAULT_PREFLIGHT_CONFIG: PreflightConfig = {
  version: "1.0.0",
  name: "agent-preflight",
  description: undefined,
  runtime: {
    environment: "development",
    nodeEnv: "development",
    debug: false,
    logLevel: "INFO",
    concurrency: 4,
    shutdownTimeout: 30000,
    gracefulShutdown: true,
    tempDir: "./tmp",
    dataDir: "./data",
    cache: {
      enabled: true,
      ttl: 300000,
      maxSize: 104857600,
    },
    scheduling: {
      maxQueueSize: 1000,
      pollingInterval: 100,
      preemptionEnabled: true,
    },
  },
  security: {
    encryption: {
      enabled: true,
      algorithm: "AES-256-GCM",
      keyRotationDays: 90,
    },
    authentication: {
      enabled: true,
      provider: "JWT",
      tokenExpiry: 3600000,
      refreshTokenExpiry: 604800000,
      requireApiKey: true,
    },
    authorization: {
      enabled: true,
      defaultRole: "viewer",
      roles: {
        admin: ["*"],
        operator: ["agent:read", "agent:write", "task:read", "task:write", "system:read"],
        viewer: ["agent:read", "task:read", "system:read"],
      },
    },
    sandbox: {
      enabled: true,
      runtime: "DENO",
      memoryLimit: 524288000,
      cpuLimit: 0.5,
      networkAccess: false,
      allowedDomains: [],
      allowedModules: [],
      timeout: 30000,
      readOnlyFilesystem: true,
    },
    rateLimiting: {
      enabled: true,
      maxRequests: 1000,
      windowMs: 60000,
      strategy: "TOKEN_BUCKET",
      burstAllowed: 10,
    },
    auditLogging: {
      enabled: true,
      retentionDays: 90,
      events: [],
    },
  },
  api: {
    port: 4000,
    host: "0.0.0.0",
    basePath: "/api/v1",
    cors: {
      enabled: true,
      origins: ["*"],
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
      allowedHeaders: ["Content-Type", "Authorization"],
      credentials: true,
      maxAge: 86400,
    },
    bodyLimit: 1048576,
    timeout: 30000,
    compression: true,
    trustProxy: false,
    rateLimit: {
      enabled: true,
      maxRequests: 100,
      windowMs: 60000,
    },
    ssl: {
      enabled: false,
      cert: undefined,
      key: undefined,
    },
  },
  observability: {
    tracing: {
      enabled: true,
      samplingRate: 0.1,
      exporter: "CONSOLE",
      batchSize: 100,
      batchInterval: 5000,
      endpoint: undefined,
    },
    metrics: {
      enabled: true,
      exporter: "CONSOLE",
      batchSize: 100,
      batchInterval: 10000,
      endpoint: undefined,
      prefix: "preflight_",
    },
    logging: {
      level: "INFO",
      format: "JSON",
      output: "CONSOLE",
      filePath: undefined,
      maxFileSize: 10485760,
      maxFiles: 5,
      includeTimestamp: true,
      includeCorrelationId: true,
      colorize: true,
    },
    healthCheck: {
      enabled: true,
      path: "/health",
      interval: 30000,
      timeout: 5000,
    },
  },
  memory: {
    defaultLayer: "WORKING",
    maxEntriesPerAgent: 10000,
    maxEntrySize: 1048576,
    ttl: {
      WORKING: 300000,
      SESSION: 3600000,
      LONG_TERM: 2592000000,
      SEMANTIC: 2592000000,
      KNOWLEDGE_GRAPH: 2592000000,
      VECTOR: 2592000000,
      PROJECT: 604800000,
      USER: 2592000000,
      SHARED: 2592000000,
      ENCRYPTED: 3600000,
    },
    vectorDimension: 1536,
    similarityMetric: "cosine",
    encryptionEnabled: false,
    storage: {
      type: "MEMORY",
      connectionString: undefined,
      poolSize: 10,
    },
  },
  plugins: {
    enabled: true,
    directory: "./plugins",
    autoLoad: false,
    allowlist: [],
    blocklist: [],
    timeout: 30000,
    maxMemory: 268435456,
    permissions: {
      requireExplicitConsent: true,
      defaultPermissions: [],
    },
    registries: [],
  },
  deployment: undefined,
  agents: [],
  providers: [],
};
